### ISSUE TITLE
I can't launch EPRtoolbox (multiple errors)

### ISSUE THREAD

**Issue by NerosTie** [morganbye/EPRtoolbox#2]
The plugin is installed but when I type `EPRtoolbox` in MATLAB (R2016a) I can see the UI for 0.1s then it crashs:

``` matlab
>> EPRtoolbox
Error using imread (line 349)
File "" does not exist.

Error in EPRtoolbox>EPRtoolbox_OpeningFcn (line 121)
logo_mb = imread(logo_mb);

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure),
    varargin{:});

Error in EPRtoolbox (line 97)
    gui_mainfcn(gui_State, varargin{:});
```

I'm doing something wrong?

**Comment by morganbye** [comment]
Sorry for not getting back to you sooner, apparently git doesn't notify me anymore.

This is part of a problem with MatLab, they've massively overhauled the way that graphical user interfaces work and you'll find that a huge number of programs (with a little bit of googling are affected).

The short answer there isn't much I can do to fix this without getting a MatLab license (as I haven't touched MatLab in about 2 years). Let me check something though....

**Comment by morganbye** [comment]
OK, yeah, there's no way for me to modify the GUI without a MatLab install.

However, all of the functions that are in the GUI are callable directly from the normal MatLab command line.

i.e. if you want to load a Bruker file. You just need to type
`BrukerRead` 
and that function will take care of the rest. The GUI was just a nice way to sit on top of the underlying scripts and bring them together.

You can check out example usage for all the scripts over at morganbye.net/eprtoolbox
